//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.16 at 07:42:36 PM EAT 
//


package com.ceres.springsoap.soap;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinalResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinalResultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Winner" type="{http://soap.springsoap.ceres.com}WinnerType"/&gt;
 *         &lt;element name="TotalRounds" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinalResultType", propOrder = {
    "winner",
    "totalRounds"
})
public class FinalResultType {

    @XmlElement(name = "Winner", required = true)
    @XmlSchemaType(name = "string")
    protected WinnerType winner;
    @XmlElement(name = "TotalRounds")
    protected int totalRounds;

    /**
     * Gets the value of the winner property.
     * 
     * @return
     *     possible object is
     *     {@link WinnerType }
     *     
     */
    public WinnerType getWinner() {
        return winner;
    }

    /**
     * Sets the value of the winner property.
     * 
     * @param value
     *     allowed object is
     *     {@link WinnerType }
     *     
     */
    public void setWinner(WinnerType value) {
        this.winner = value;
    }

    /**
     * Gets the value of the totalRounds property.
     * 
     */
    public int getTotalRounds() {
        return totalRounds;
    }

    /**
     * Sets the value of the totalRounds property.
     * 
     */
    public void setTotalRounds(int value) {
        this.totalRounds = value;
    }

}
