//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.16 at 07:42:36 PM EAT 
//


package com.ceres.springsoap.soap;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ceres.springsoap.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ceres.springsoap.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RockPaperScissorsMatch }
     * 
     */
    public RockPaperScissorsMatch createRockPaperScissorsMatch() {
        return new RockPaperScissorsMatch();
    }

    /**
     * Create an instance of {@link RockPaperScissorsMatch.Players }
     * 
     */
    public RockPaperScissorsMatch.Players createRockPaperScissorsMatchPlayers() {
        return new RockPaperScissorsMatch.Players();
    }

    /**
     * Create an instance of {@link RockPaperScissorsMatch.Rounds }
     * 
     */
    public RockPaperScissorsMatch.Rounds createRockPaperScissorsMatchRounds() {
        return new RockPaperScissorsMatch.Rounds();
    }

    /**
     * Create an instance of {@link FinalResultType }
     * 
     */
    public FinalResultType createFinalResultType() {
        return new FinalResultType();
    }

    /**
     * Create an instance of {@link PlayerType }
     * 
     */
    public PlayerType createPlayerType() {
        return new PlayerType();
    }

    /**
     * Create an instance of {@link RoundType }
     * 
     */
    public RoundType createRoundType() {
        return new RoundType();
    }

}
