//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.16 at 07:42:36 PM EAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soap.springsoap.ceres.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ceres.springsoap.soap;
