//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.16 at 07:42:36 PM EAT 
//


package com.ceres.springsoap.soap;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoundType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoundType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RoundNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Player1Move" type="{http://soap.springsoap.ceres.com}MoveType"/&gt;
 *         &lt;element name="Player2Move" type="{http://soap.springsoap.ceres.com}MoveType"/&gt;
 *         &lt;element name="Winner" type="{http://soap.springsoap.ceres.com}WinnerType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoundType", propOrder = {
    "roundNumber",
    "player1Move",
    "player2Move",
    "winner"
})
public class RoundType {

    @XmlElement(name = "RoundNumber")
    protected int roundNumber;
    @XmlElement(name = "Player1Move", required = true)
    @XmlSchemaType(name = "string")
    protected MoveType player1Move;
    @XmlElement(name = "Player2Move", required = true)
    @XmlSchemaType(name = "string")
    protected MoveType player2Move;
    @XmlElement(name = "Winner", required = true)
    @XmlSchemaType(name = "string")
    protected WinnerType winner;

    /**
     * Gets the value of the roundNumber property.
     * 
     */
    public int getRoundNumber() {
        return roundNumber;
    }

    /**
     * Sets the value of the roundNumber property.
     * 
     */
    public void setRoundNumber(int value) {
        this.roundNumber = value;
    }

    /**
     * Gets the value of the player1Move property.
     * 
     * @return
     *     possible object is
     *     {@link MoveType }
     *     
     */
    public MoveType getPlayer1Move() {
        return player1Move;
    }

    /**
     * Sets the value of the player1Move property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoveType }
     *     
     */
    public void setPlayer1Move(MoveType value) {
        this.player1Move = value;
    }

    /**
     * Gets the value of the player2Move property.
     * 
     * @return
     *     possible object is
     *     {@link MoveType }
     *     
     */
    public MoveType getPlayer2Move() {
        return player2Move;
    }

    /**
     * Sets the value of the player2Move property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoveType }
     *     
     */
    public void setPlayer2Move(MoveType value) {
        this.player2Move = value;
    }

    /**
     * Gets the value of the winner property.
     * 
     * @return
     *     possible object is
     *     {@link WinnerType }
     *     
     */
    public WinnerType getWinner() {
        return winner;
    }

    /**
     * Sets the value of the winner property.
     * 
     * @param value
     *     allowed object is
     *     {@link WinnerType }
     *     
     */
    public void setWinner(WinnerType value) {
        this.winner = value;
    }

}
