//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.16 at 07:42:36 PM EAT 
//


package com.ceres.springsoap.soap;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WinnerType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="WinnerType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PLAYER1"/&gt;
 *     &lt;enumeration value="PLAYER2"/&gt;
 *     &lt;enumeration value="DRAW"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "WinnerType")
@XmlEnum
public enum WinnerType {

    @XmlEnumValue("PLAYER1")
    PLAYER_1("PLAYER1"),
    @XmlEnumValue("PLAYER2")
    PLAYER_2("PLAYER2"),
    DRAW("DRAW");
    private final String value;

    WinnerType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WinnerType fromValue(String v) {
        for (WinnerType c: WinnerType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
